platform: linux/amd64

workspace:
  base: /go
  path: src/github.com/drone/drone

pipeline:
  build:
    image: golang:1.8
    commands:
      - go get -u github.com/cyberb/drone-ui/dist
      - mv /go/src/github.com/cyberb/drone-ui /go/src/github.com/drone/drone-ui
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - apt-get install apt-transport-https
      - apt-get update && apt-get install yarn
      - cd ../drone-ui
      - yarn install
      - yarn run build
      - go get -u golang.org/x/tools/cmd/cover
      - go get -u golang.org/x/net/context
      - go get -u golang.org/x/net/context/ctxhttp
      - go get -u github.com/golang/protobuf/proto
      - go get -u github.com/golang/protobuf/protoc-gen-go
      - go get github.com/bradrydzewski/togo
      - go build github.com/bradrydzewski/togo
      - go generate github.com/drone/drone-ui/...
      - go install github.com/drone/drone-ui/...
      - go build -ldflags '-extldflags "-static" -X github.com/drone/drone/version.VersionDev=build.'${DRONE_BUILD_NUMBER} -o release/drone-server github.com/drone/drone/cmd/drone-server
      - ls -la release/drone-server
  
  publish_server:
    image: plugins/docker
    repo: syncloud/drone
    secrets: [ docker_username, docker_password ]
    tag: [ latest ]
    when:
      branch: master
      event: push
